---

timezone: Europe/London


# role: email
mail_account: gandi
mail_server: mail.gandi.net
mail_port: 587
mail_from: "{{hostname}}@{{private_my_mail_domain}}"
mail_domain: "{{private_my_mail_domain}}"
mail_username: "{{private_my_mail_username}}"
mail_password: "{{private_my_mail_password}}"
mail_root_email: "{{private_my_email}}"
mail_default_email: "{{private_my_email}}"
mail_server_hostname: "{{hostname_fqdn}}"

# role: restic-backup
b2_account_id:  "{{private_b2_account_id}}"
b2_account_key: "{{private_b2_account_key}}"
restic_password: "{{private_restic_password}}"
restic_repository: "b2:ejsmit-{{hostname}}-restic"

# role: certbot-gandi-dns
gandi_api_token: "{{private_gandi_api_token}}"
certbot_admin_email: "{{private_certbot_admin_email}}"
certbot_domains: "{{private_certbot_domains}}"

# traefik
letsencrypt_domain: "{{ certbot_domains[0] }}"

# role: dotfiles
dotfiles_project: ejsmit/dotfiles
fresh_install_url: https://raw.githubusercontent.com/ejsmit/fresh/master/install.sh

docker_version_armv7: "*"


# some defaults in case they are not later overridden.  Ignore them here.
host_packages: []
