---

group_required_packages:
  - mc
  - tmux
  - git
  - wget
  - curl
  - acl
  - python
  - python-pip
  - python3
  - python3-pip
  - python-apt
  - python3-apt
  - ca-certificates
  - apt-transport-https
  - software-properties-common

default_user: pi

# backup settings
restic_arch: "linux_arm"
