
- name: Install xmpp-server prosody
  block:

    - name: install prosody xmpp server
      apt:
        name: prosody
        state: latest
      register: prosody_installed

    - name: Create prosody site section
      template:
        src: virtualhost.cfg.lua
        dest: /etc/prosody/conf.avail/{{prosody_ssl_domain}}.cfg.lua
        owner: root
        group: root
        mode: "0644"

    - name: Create a link to activate site config
      file:
        src: "../conf.avail/{{prosody_ssl_domain}}.cfg.lua"
        path: "/etc/prosody/conf.d/{{prosody_ssl_domain}}.cfg.lua"
        state: link

    - name: Create script to update certificates
      template:
        src: update_prosody_certs.sh
        dest: /usr/local/bin/update_prosody_certs.sh
        owner: root
        group: root
        mode: "0755"

    - name: run script to update certs
      command: /usr/local/bin/update_prosody_certs.sh


    - name: enable and start prosody server
      service:
        name: prosody
        enabled: true
        state: restarted

    - name: create prosody users (only when new server installed/upgraded)
      command: prosodyctl register {{item}} {{prosody_chat_domain}} {{item}}
      with_items: "{{ prosody_users }}"
      when: prosody_installed.changed

    - name: Add cron job for certificate  update
      cron:
        name: prosody-certs
        job: /usr/local/bin/update_prosody_certs.sh
        hour: 2
        minute: 30
        weekday: 0
        user: root
        cron_file: prosody-certs

  when: xmpp_server == true


- name: install mcabber xmpp console client
  block:

    - name: install console mcabber client
      apt:
        name: mcabber
        state: latest

    - name: create config directory
      file:
        path: "/home/{{default_user}}/.config/mcabber"
        state: directory
        owner: "{{default_user}}"
        group: "{{default_user}}"
        mode: "0700"

    - name: Create mcabber config file
      template:
        src: mcabberrc
        dest: "/home/{{default_user}}/.config/mcabber/mcabberrc"
        owner: "{{default_user}}"
        group: "{{default_user}}"
        mode: "0600"

  when: xmpp_console_client == true
