
- name: Install xmpp-server prosody
  block:

    - name: install prosody xmpp server
      apt:
        name: prosody
        state: latest
      register: prosody_installed

    - name: Create prosody site section
      template:
        src: virtualhost.cfg.lua
        dest: /etc/prosody/conf.avail/{{prosody_ssl_domain}}.cfg.lua
        owner: root
        group: root
        mode: "0644"

    - name: Create a link to activate site config
      file:
        src: "../conf.avail/{{prosody_ssl_domain}}.cfg.lua"
        path: "/etc/prosody/conf.d/{{prosody_ssl_domain}}.cfg.lua"
        state: link

    - name: Copy certificate from letsencrypt
      command: >
          cp /etc/letsencrypt/live/{{prosody_ssl_domain}}/fullchain.pem
          /etc/prosody/certs/{{prosody_ssl_domain}}.crt
      when: prosody_installed.changed

    - name: fix certificate permissions
      file:
        path: "/etc/prosody/certs/{{prosody_ssl_domain}}.crt"
        owner: root
        group: root
        mode: "0644"

    - name: Copy key from letsencrypt
      command: >
          cp /etc/letsencrypt/live/{{prosody_ssl_domain}}/privkey.pem
          /etc/prosody/certs/{{prosody_ssl_domain}}.key
      when: prosody_installed.changed

    - name: fix key permissions
      file:
        path: "/etc/prosody/certs/{{prosody_ssl_domain}}.key"
        owner: root
        group: prosody
        mode: "0640"

    - name: enable and start prosody server
      service:
        name: prosody
        enabled: true
        state: restarted

    - name: create prosody users (only when new server installed/upgraded)
      command: prosodyctl register {{item}} {{prosody_chat_domain}} {{item}}
      with_items: "{{ prosody_users }}"
      when: prosody_installed.changed

  when: xmpp_server == true


- name: install mcabber xmpp console client
  block:

    - name: install console mcabber client
      apt:
        name: mcabber
        state: latest

    - name: Create mcabber config file
      template:
        src: mcabberrc
        dest: "/home/{{regular_username}}/.config/mcabber/mcabberrc"
        owner: "{{regular_username}}"
        group: "{{regular_username}}"
        mode: "0644"

  when: xmpp_console_client == true
