---

- name: Install restic backup
  apt:
    name: restic
    state: latest


- name: create restic script
  template:
    src: restic-backup.sh
    dest: /usr/local/bin/restic-backup.sh
    mode: "0755"

- name: create restic restore latest to home script
  template:
    src: restic-restore-latest-to-home.sh
    dest: /usr/local/bin/restic-restore-latest-to-home.sh
    mode: "0755"

- name: install restic password file
  copy:
    content: "{{restic_password}}"
    dest: "{{restic_password_file}}"
    mode: "0600"

- name: install restic environment file
  template:
    src: restic-environment
    dest: "{{restic_environment_file}}"
    mode: "0600"

- name: create backup scripts directory
  file:
    path: /etc/mybackup/scripts.d
    state: directory
    mode: 0755

- name: install backup script
  copy:
    src: backup.sh
    dest: /etc/mybackup/backup.sh
    mode: 0755

- name: install backup conf
  template:
    src: backup.conf
    dest: /etc/mybackup/backup.conf

- name: install backup data scripts
  copy:
    src: files/{{item}}.sh
    dest: /etc/mybackup/scripts.d/{{item}}
    mode: "0755"
  with_items: "{{backup_scripts}}"

- name: install daily backup cron job
  cron:
    name: "daily backup"
    minute: "30"
    hour: "5"
    weekday: "{{backup_day_of_week}}"
    job: "/etc/mybackup/backup.sh >/dev/null 2>&1"
    cron_file: mybackup
    user: root

- name: install weekly prune cron script
  copy:
    src: files/restic-backup-prune.sh
    dest: /etc/cron.weekly/
    mode: "0755"
