---

- name: check if nextcloud already installed
  shell: snap list nextcloud
  register: snap_exists
  ignore_errors: true


- name: install nextcloud snap
  block:

    - name: install nextcloud
      command: snap install nextcloud

    - name: allow the use of external disks
      command: snap connect nextcloud:removable-media :removable-media

    - name: Auto first run configure wizard
      command: snap run nextcloud.manual-install {{nextcloud_user}} "{{nextcloud_pass}}"

    - name: add trusted host {{hostname}}
      command: snap run nextcloud.occ config:system:set trusted_domains 1 --value={{hostname}}

    - name: add trusted host {{hostname_fqdn}}
      command: snap run nextcloud.occ config:system:set trusted_domains 2 --value={{hostname_fqdn}}


  when: snap_exists.rc > 0


# Start and stop it to make sure all config is created.

- name: start  nextcloud
  command: snap start nextcloud

- name: stop  nextcloud
  command: snap stop nextcloud





- name: Update data directory to point to external disk
  lineinfile:
    dest: /var/snap/nextcloud/current/nextcloud/config/config.php
    regexp: "'datadirectory' =>"
    line: "  'datadirectory' => '{{nextcloud_data_directory}}/data',"
    state: present

- name: create nextcloud directory on external disk
  file:
    path: "{{nextcloud_data_directory}}"
    state: directory
    mode: 0755

- name: move nextcloud files to external disks
  command: mv /var/snap/nextcloud/common/nextcloud/data {{nextcloud_data_directory}}

- name: check ownership of moves files
  command: chown -R root:root {{nextcloud_data_directory}}

- name: check permissions of moved files
  command: chmod -R 0770 {{nextcloud_data_directory}}





- name: enable https support
  command: snap run nextcloud.enable-https custom {{https_cert_path}}/{{https_cert}}  \
                                                  {{https_cert_path}}/{{https_key}} \
                                                  {{https_cert_path}}/{{https_chain}}

- name: delete temp certificates
  file:
    state: absent
    path: "{{ item }}"
  with_items:
    - "{{https_cert_path}}/{{https_cert}}"
    - "{{https_cert_path}}/{{https_key}}"
    - "{{https_cert_path}}/{{https_chain}}"


- name: start nextcloud
  command: snap start nextcloud
