# gandalf.local
# Kubuntu

- name: a playbook to configure gandalf.local
  hosts: gandalf.local
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml


  handlers:
  - include: handlers/reboot.yml

  roles:
    - deb-packages
    - dotfiles
    - motd
    - desktop-common
    - kde-config
    - geerlingguy.docker
