

- name: a playbook to configure gollum.home
  hosts: gollum.home
  remote_user: deploy
  become: true

#  vars:
#    samba_image: "ejsmit/samba:armhf"

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vars/minio.vault.yml
    - vars/samba.vault.yml
    - vars/nextcloud-client.vault.yml
    - vars/nextcloud-admin.vault.yml

  handlers:
  - include: handlers/reboot.yml

  collections:
    - ejsmit.containers

  roles:
    # - mount-usb-disk
    # - nextcloud-client-tools
    # - install_certs
    # - geerlingguy.docker_arm
    - docker-common
    - docker-samba-pi
    # - docker-nextcloud
    # - docker-wallabag
    # - docker-minio


  tasks:


# --------------------------
#   forced reboot
# --------------------------

  # - debug: msg="Trigger Reboot"
  #   notify: reboot and wait
  #   changed_when: true
