

- name: a playbook to configure gollum.local
  hosts: gollum.local
  become: true
  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/gollum.local.yml
    - vault_vars/nextcloud.yml

  handlers:
  - include: handlers/reboot.yml

  tasks:


# --------------------------
#   pi roles
# --------------------------

  - name: common raspberry pi config
    include_role:
      name: pi-common

  - name: raspberry pi packages
    include_role:
      name: pi-packages



# --------------------------
#   reboot if we need to
# --------------------------

  - name: reboot if we need to
    meta: flush_handlers


# --------------------------
#   Mount disk
# --------------------------

  - name: mount external disk
    include_role:
      name: mount-usb-disk




# --------------------------
#   various roles
# --------------------------

  - name: Install and configure dotfiles
    block:
    - name: install dotfiles
      include_role:
        name: dotfiles
    become_user: "{{default_user}}"

  - name: Install and configure email
    include_role:
      name: email

  - name: Install and configure unattended upgrades
    include_role:
      name: unattended-upgrades

  - name: Install and configure nextcloud client tools
    include_role:
      name: nextcloud-client-tools

  - name: Install and configure restic backups
    include_role:
      name: restic-backups

  - name: Install and configure logwatch
    include_role:
      name: logwatch


# --------------------------
#   docker and samba
# --------------------------

  - name: Install docker
    include_role:
      name: docker

  - name: Install samba
    include_role:
      name: docker-samba




# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
