
- name: a playbook to update a raspberry pi
  hosts: "{{ host | default('pi_servers') }}"
  remote_user: deploy
  become: true
  vars_files:
    - vars/ssh-certs.vault.yml
  handlers:
  - include: handlers/reboot.yml

  roles:
    - deb-packages
    - dotfiles
    - ssh-certs

  tasks:



# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
