
- name: a playbook to update a raspberry pi
  hosts: "{{ host | default('servers') }}"
  remote_user: deploy
  become: true

  handlers:
  - include: handlers/reboot.yml

  roles:
    - deb-packages

  tasks:



# --------------------------
#   forced reboot
# --------------------------

  # - debug: msg="Trigger Reboot"
  #   notify: reboot and wait
  #   changed_when: true
