# glaurung.local
# assume raspbian base image

- name: a playbook to configure generic raspberry pi server
  hosts: '{{ host }}'
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/{{ host }}.yml
    - vault_vars/nextcloud.yml


  handlers:
  - include: handlers/reboot.yml

  roles:
    - pi-common
    - deb-packages
    - dotfiles
    - email
    - unattended-upgrades
    - logwatch

  tasks:


# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
