---
roles:
  - name: geerlingguy.docker
  - name: geerlingguy.docker_arm
  - name: geerlingguy.postgresql
  - name: geerlingguy.apache

collections:
#   - name: geerlingguy.k8s
#    version: 0.9.3
  - name: community.zabbix
    version: 1.1.0
