# smaug.local
# assume raspbian base image

- name: a playbook to configure smaug.local
  hosts: smaug.local
  become: true
  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/smaug.local/main.yml

  handlers:
  - include: handlers/reboot.yml

  tasks:

# --------------------------
#   pi-common
# --------------------------

  - name: common raspberry pi config
    include_role:
      name: pi-common


# --------------------------
#   ipv6 mac based address
# --------------------------

  - name: ipv6 hardware based address
    lineinfile:
      dest: /etc/dhcpcd.conf
      state: present
      backup: yes
      regexp: '^slaac'
      line: 'slaac hwaddr'
    notify: reboot and wait

# --------------------------
#   nightly reboots
# --------------------------

  - cron:
      name: "Auto reboot"
      minute: "3"
      hour: "3"
      job: "/sbin/shutdown -r now"
      cron_file: reboot
      user: root


# --------------------------
#   reboot if we need to
# --------------------------

  - name: reboot if we need to
    meta: flush_handlers



# --------------------------
#   various roles
# --------------------------

  - name: Install and configure firewall
    include_role:
      name: ufw-firewall

  - name: Install and configure email
    include_role:
      name: email

  - name: Install and configure unattended upgrades
    include_role:
      name: unattended-upgrades

  - name: Install and configure restic backups
    include_role:
      name: restic-backups

  - name: Install and configure logwatch
    include_role:
      name: logwatch

# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
