# smaug.local
# assume raspbian base image

- name: a playbook to configure smaug.local
  hosts: smaug.local
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/smaug.local.yml
    - vault_vars/nextcloud.yml

  handlers:
  - include: handlers/reboot.yml

  tasks:



# --------------------------
#   various roles
# --------------------------

#  - name: Install and configure dotfiles
#    block:
#    - name: install dotfiles
#      include_role:
#        name: dotfiles
#    become_user: "{{default_user}}"


  - name: Install and configure restic backups
    include_role:
      name: restic-backups

  - name: Install and configure certbot
    include_role:
      name: certbot-gandi-dns




# --------------------------
#   nightly reboots
# --------------------------

  - cron:
      name: "Auto reboot"
      minute: "15"
      hour: "3"
      job: "/sbin/shutdown -r now"
      cron_file: reboot
      user: root


# --------------------------
#   pihole prep
# --------------------------


  - name: Prepare for pihole installation
    include_role:
      name: pihole



# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
