# smaug.local
# assume raspbian base image
# assume pi-server-setup completed successfully.



- name: a playbook to configure smaug.local
  hosts: smaug.local
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/smaug.local.yml
    - vault_vars/nextcloud.yml

  handlers:
  - include: handlers/reboot.yml

  roles:
    - nextcloud-client-tools
    - certbot-gandi-dns
    - restic-backups
    - pihole

  tasks:


  - cron:
      name: "Auto nightly reboot"
      minute: "15"
      hour: "3"
      job: "/sbin/shutdown -r now"
      cron_file: reboot
      user: root

# --------------------------
#   forced reboot
# --------------------------

  - debug: msg="Trigger Reboot"
    notify: reboot and wait
    changed_when: true
