# glaurung.local
# assume raspbian base image

- name: a playbook to configure glaurung.local
  hosts: glaurung.local
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vault_vars/glaurung.local.yml
    - vault_vars/nextcloud.yml
    
  handlers:
  - include: handlers/reboot.yml

  tasks:



  # - name: Install and configure dotfiles
  #   block:
  #     - name: install dotfiles
  #       include_role:
  #         name: dotfiles
  #   become_user: "{{default_user}}"


# --------------------------
#   Docker, etc.
# --------------------------

  # - name: Install role docker
  #   include_role:
  #     name: docker

  # - name: Install role docker-management
  #   include_role:
  #     name: docker-management

  # - name: install role kubernetes
  #   include_role:
  #     name: kubernetes

  # - name: install role kubernetes-management
  #   include_role:
  #     name: kubernetes-management

  - name: install role kubernetes-redis
    include_role:
      name: kubernetes-redis


# --------------------------
#   forced reboot
# --------------------------

  # - debug: msg="Trigger Reboot"
  #   notify: reboot and wait
  #   changed_when: true
