# thorin.local
# assume raspbian base image

- name: a playbook to configure thorin.local
  hosts: thorin.local
  remote_user: deploy
  become: true

  vars_files:
    - ~/.private/ansible/vars/me-myself-and-i.yml
    - vars/nextcloud-client.vault.yml

  handlers:
  - include: handlers/reboot.yml

  collections:
    - ejsmit.containers

  roles:
    - nextcloud-client-tools
    - install_certs
    - geerlingguy.docker_arm
    # - docker-common


  tasks:





# --------------------------
#   forced reboot
# --------------------------

  # - debug: msg="Trigger Reboot"
  #   notify: reboot and wait
  #   changed_when: true
