

- name: Run the equivalent of "apt dist-upgrade"
  apt:
    update_cache: yes
    upgrade: dist
  notify: reboot and wait

- name: install new packages
  apt:
    name: "{{all_requried_packages + os_required_packages + host_required_packages}}"
    state: latest
  notify: reboot and wait

- name: Reboot if any packages were installed.
  meta: flush_handlers
