---

- name: ensure share mount directory exists
  file:
    path: "{{ samba_data }}"
    state: directory
    mode: 0775
    owner: root
    group: root


- name: ensure samba shares directories exist
  file:
    path: "{{ samba_data }}/{{item}}"
    state: directory
    mode: 775
    owner: root
    group: root
  with_items: "{{ samba_shares_list }}"


- name: Copy samba compose file
  template:
    src: templates/docker-compose-samba.yml
    dest: /home/{{default_user}}/docker-compose-samba.yml
    mode: "0644"


- name: start samba using docker compose
  command: docker-compose -f /home/{{default_user}}/docker-compose-samba.yml up --detach
