#!/bin/sh


[ -r /etc/lsb-release ] && . /etc/lsb-release

if [ -z "$DISTRIB_DESCRIPTION" ] && [ -x /usr/bin/lsb_release ];
then
  # Fall back to using the very slow lsb_release utility
  DISTRIB_DESCRIPTION=$(lsb_release -s -d)
fi

cat /etc/motd_banner
printf "\n"

printf "\t%s \t\t\e[1mKernel\e[0m %s\n" "$DISTRIB_DESCRIPTION" "$(uname -r)"
/usr/bin/uptime

printf "\n"
