version: "3"
services:
  samba:
#    network_mode: bridge
    image: "{{samba_image}}"
    restart: unless-stopped
    volumes:
{% for vol in samba_volumes %}
      - {{ vol }}
{% endfor %}
    ports:
{% for port in samba_ports %}
      - {{ port }}
{% endfor %}
    command: -p -r {{samba_users}} {{samba_shares}}
