version: "3"
services:
  watchtower:
    image: containrrr/watchtower:{{docker_watchtower_tag}}
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    command: --schedule "0 4 * * * *" --cleanup
