



# - name: Watchtower for auto updates for containers
#   include_tasks: watchtower.yml
#   when: docker_watchtower is defined


# - name: Traefik as a http reverse proxy
#   include_tasks: traefik.yml
  # when: docker_traefik is defined

# - name: Portainer as a http reverse proxy
#   include_tasks: portainer.yml
  # when: docker_traefik is defined
