---

- name: Copy portainer compose file
  template:
    src: templates/docker-compose-portainer.yml
    dest: /home/{{default_user}}/docker-compose-portainer.yml
    mode: "0644"


- name: start portainer using docker compose
  command: docker-compose -f /home/{{default_user}}/docker-compose-portainer.yml up --detach
