---

- name: Update login screen users (1/2)
  ini_file:
    path: /etc/sddm.conf
    section: Users
    option: HideUsers
    value: deploy

- name: Update login screen users (2/2)
  ini_file:
    path: /etc/sddm.conf
    section: Users
    option: HideShells
    value: /usr/sbin/nologin,/sbin/nologin,/bin/false



# start block for become default user
# - block:
# dashes 4 indent inside block



    # - name: Konsole profile copy
    #   copy:
    #     src: files/RassieSmit.profile
    #     dest: ~/.local/share/konsole/RassieSmit.profile
    #     force: no
    #
    # - name: yakuake config copy
    #   copy:
    #     src: files/yakuakerc
    #     dest: ~/.config/yakuakerc
    #     force: no
    #
    # - name: Update konsole default profile
    #   ini_file:
    #     path: ~/.config/konsolerc
    #     section: Desktop Entry
    #     option: DefaultProfile
    #     value: RassieSmit.profile

# For KDE 4
# killall plasma-desktop && kstart plasma-desktop

# For KDE 5 < 5.10
# killall plasmashell && kstart plasma-desktop

# For KDE > 5.10
# kquitapp5 plasmashell || killall plasmashell && kstart5 plasmashell




# end block for become default user (2 indent)
#  become_user: "{{default_user}}"
