---

- name: remove rainbow splash
  lineinfile:
    dest: /boot/config.txt
    regexp: 'disable_splash'
    line: 'disable_splash=1'
    state: present

- name: remove boot raspberry images
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!logo.nologo).)*)$'
    line: '\1 logo.nologo'

- name: boot parameters - quiet
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!quiet).)*)$'
    line: '\1 quiet'

- name: boot parameters - splash
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!splash).)*)$'
    line: '\1 splash'

- name: boot parameters - plymouth.ignore-serial-consoles
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!plymouth.ignore-serial-consoles).)*)$'
    line: '\1 plymouth.ignore-serial-consoles'

- name: boot parameters - vt.global_cursor_default=0
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!vt.global_cursor_default=0).)*)$'
    line: '\1 vt.global_cursor_default=0'

- name: boot parameters - console on tty3
  replace:
    path: /boot/cmdline.txt
    regexp: 'console=tty1'
    replace: 'console=tty3'


- name: create plymouth theme directory
  file:
    path: /usr/share/plymouth/themes/simple
    state: directory
    mode: 0755

- name: install plymouth theme
  copy:
    src: files/simple.plymouth
    dest: /usr/share/plymouth/themes/simple/simple.plymouth

- name: install plymouth theme script
  copy:
    src: files/simple.script
    dest: /usr/share/plymouth/themes/simple/simple.script

- name: install background image
  copy:
    src: files/wallpaper.txt
    dest: /etc/plymouth/wallpaper.png
