
# requires playbook reboot and wait handler.


- name: change pi user password
  user:
    name: pi
    password: "{{ pi_password_hash }}"

- name: get current timezone
  command: cat /etc/timezone
  register: current_timezone
  changed_when: false

- name: fix timezone if required
  command: timedatectl set-timezone {{timezone}}
  when: current_timezone.stdout != timezone


- name: disable serial port
  lineinfile:
    dest: /boot/config.txt
    regexp: "enable_uart="
    line: "enable_uart=0"
    state: present
  notify: reboot and wait

- name: remove serial getty
  replace:
    path: /boot/cmdline.txt
    regexp: ' console=serial0,115200'
    replace: ''
  notify: reboot and wait


- name: stop trigger happy hotkey service
  systemd:
    name: triggerhappy.service
    state: stopped
    enabled: false

- name: remove rainbow splash
  lineinfile:
    dest: /boot/config.txt
    regexp: 'disable_splash'
    line: 'disable_splash=1'
    state: present

- name: remove boot raspberry images
  lineinfile:
    dest: /boot/cmdline.txt
    backrefs: True
    state: present
    regexp: '(^((?!logo.nologo).)*)$'
    line: '\1 logo.nologo'

- name: disable bluetooth & wifi
  lineinfile:
    dest: /boot/config.txt
    state: present
    regexp: '^dtoverlay='
    line: 'dtoverlay=disable-wifi,disable-bt'
  when: disable_wifi_bt == true
  notify: reboot and wait

- name: stop hciaurt when wifi isdisabled
  systemd:
    name: hciuart
    state: stopped
    enabled: false
  when: disable_wifi_bt == true

- name: reboot if we need to
  meta: flush_handlers
