
- name: check for certificates
  stat:
    path: /etc/letsencrypt/live
  register: cert_stat

- name: fail if certs do not exist
  fail:
    msg: "Whoops! certs missing"
  when: cert_stat.stat.isdir is not defined



- name: test of secret already exists
  command: kubectl get secret letsencrypt-certs
  register: cert_exists
  ignore_errors: yes
  failed_when: false

- name: generate secret containing ssl certificate for website
  command: >
    kubectl create secret tls letsencrypt-certs
    --cert=/etc/letsencrypt/live/smit.org.uk/fullchain.pem
    --key=/etc/letsencrypt/live/smit.org.uk/privkey.pem
  when: cert_exists.rc > 0
