



- name:  nextcloud container
  docker_container:
    name: nextcloud
    image: "{{ nextcloud_image }}"
    state: started
    restart_policy: unless-stopped
    networks_cli_compatible: yes
    networks:
      - name: "{{nextcloud_network}}"
      - name: frontend_net
      - name: backend_net
    volumes:
      - "{{nextcloud_datadir}}/html:/var/www/html"
      - "{{nextcloud_datadir}}/data:/var/www/html/data"
      - "{{nextcloud_datadir}}/config:/var/www/html/config"
    env:
      MYSQL_HOST: nextcloud-db
      MYSQL_DATABASE: "{{ nextcloud_mysql_database }}"
      MYSQL_USER: "{{ nextcloud_mysql_user }}"
      MYSQL_PASSWORD: "{{ nextcloud_mysql_password }}"
      NEXTCLOUD_ADMIN_USER: "{{nextcloud_admin_user}}"
      NEXTCLOUD_ADMIN_PASSWORD: "{{nextcloud_admin_password}}"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.{{letsencrypt_domain}}"
      NEXTCLOUD_DATA_DIR: "/var/www/html/data"
      MAIL_FROM_ADDRESS: "nextcloud"
      MAIL_DOMAIN: "{{nextcloud_mail_domain}}"
      SMTP_HOST: "smtp"
      REDIS_HOST: nextcloud-redis
      OVERWRITEPROTOCOL: "https"
      TRUSTED_PROXIES: "traefik"
      REDIS_HOST_PASSWORD: "{{nextcloud_redis_password}}"
    labels:
      traefik.enable: "true"
      traefik.http.middlewares.nextcloud-caldav.redirectregex.permanent: "true"
      traefik.http.middlewares.nextcloud-caldav.redirectregex.regex: "^https://(.*)/.well-known/(card|cal)dav"
      traefik.http.middlewares.nextcloud-caldav.redirectregex.replacement: "https://$1/remote.php/dav/"
      traefik.http.middlewares.nextcloud_https_redirect.redirectscheme.permanent: "true"
      traefik.http.middlewares.nextcloud_https_redirect.redirectscheme.scheme: "https"
      traefik.http.middlewares.secheaders.headers.STSSeconds: "315360000"
      traefik.http.routers.nextcloud-http.rule: "Host(`nextcloud.{{letsencrypt_domain}}`)"
      traefik.http.routers.nextcloud-http.entrypoints: "http"
      traefik.http.routers.nextcloud-http.middlewares: "nextcloud_https_redirect"
      traefik.http.routers.nextcloud.rule: "Host(`nextcloud.{{letsencrypt_domain}}`)"
      traefik.http.routers.nextcloud.entrypoints: "https"
      traefik.http.routers.nextcloud.tls: "true"
      traefik.http.routers.nextcloud.middlewares: "nextcloud-caldav, secheaders"


- name: Systemd Timer file to run nextcloud cron job
  template:
    src: nextcloud_cron.timer
    dest: /etc/systemd/system/nextcloud_cron.timer
- name: Systemd Service file to run nextcloud cron job
  template:
    src: nextcloud_cron.service
    dest: /etc/systemd/system/nextcloud_cron.service
- name: Systemd - enable nextcloud timer
  systemd:
    name: nextcloud_cron.timer
    daemon_reload: yes
    enabled: yes
    state: restarted
