


# start block for become default user
- block:
# dashes 4 indent inside block


    - name: Copy the nextcloud persistent volume file
      copy:
        src: files/nextcloud-pv.yml
        dest: $HOME/k8s/nextcloud-pv.yml

    - name: Install nextcloud-persistent volume into kubernetes
      command: kubectl apply -f $HOME/k8s/nextcloud-pv.yml


    - name: get list of helm installations
      command: helm list
      register: helm_list
      ignore_errors: yes


    - name: Copy my helm nextcloud values template
      template:
        src: templates/nextcloud-values.yml
        dest: $HOME/nextcloud-values.yml

    - name: update nextcloud using helm
      command: >
        helm upgrade my-nextcloud
        -f $HOME/nextcloud-values.yml
        stable/nextcloud
      when: "'nextcloud' in helm_list.stdout"

    - name: install nextcloud using helm
      command: >
        helm install my-nextcloud
        -f $HOME/nextcloud-values.yml
        stable/nextcloud
      when: "'nextcloud' not in helm_list.stdout"






# end block for become default user (2 indent)
  become_user: "{{default_user}}"
