apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-redis-master
  labels:
    app: redis
spec:
  selector:
    matchLabels:
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: master
        image: redis
        ports:
        - containerPort: 6379


---
apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: my-redis-master # Name of the Kubernetes resource
  labels:            # Labels that will be applied to this resource
    app: redis
spec:
  ports:
  - port: 6379       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 6379
  selector:          # Map any Pod with the specified labels to this service
    app: redis
