---

- name: Install email packages
  apt:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
      - msmtp
      - msmtp-mta
      - bsd-mailx


- name: install root config file
  template:
    src: msmtprc
    dest: /root/.msmtprc
    mode: '0600'
    owner: root
    group: root


- name: install config file for users
  template:
    src: msmtprc
    dest: /home/{{default_user}}/.msmtprc
    mode: '0600'
    owner: "{{default_user}}"
    group: "{{default_user}}"


- name: install aliases
  template:
    src: aliases
    dest: /etc/aliases
