---



- name: install required firewall packages
  apt:
    name: ufw
    state: latest


- name: enable ufw systemd service
  systemd:
    name: ufw
    state: started
    enabled: yes


- name: install my-firewall-apps
  copy:
    src: files/my-firewall-apps
    dest: /etc/ufw/applications.d/my-firewall-apps


- name: alllow firewall ssh connections
  ufw:
    rule: limit
    name: OpenSSH


- name: allow firewall applications
  ufw:
    rule: allow
    name: "{{item}}"
  with_items: "{{firewall_apps}}"


# proto igmp not in ansible ufw module.
# want to explicity deny this to prevent default policy deny logging
- name: remove igmp broadcasts from logs
  command: ufw deny in proto igmp to 224.0.0.1

- name: firewall INCOMING policy
  ufw:
    direction: incoming
    policy: deny

- name: firewall OUTGOING policy
  ufw:
    direction: outgoing
    policy: allow


- name: enable ufw
  ufw:
    state: enabled
