---


desktop_packages_ppa:
  - ppa:kubuntu-ppa/backports
  - ppa:nextcloud-devs/client
  - ppa:pbek/qownnotes
  - ppa:phoerious/keepassxc
  # - ppa:ansible/ansible
  - ppa:mank319/go-for-it


desktop_packages:
# system
  - duplicity
  - deja-dup
  - kbackup
  - yakuake
  - latte-dock
  - snapd
  - flatpak
  - direnv
  - ktorrent
  - fuse
  - gocryptfs
  - software-properties-common
  - lua5.2
  - seahorse     # useful want skype gebruik gnome-keyring
  - htop
  - powertop
  - kate
  - kwrite
  - xrdp
  - whois # for mkpasswd
# dev
  - build-essential
  - git
  - git-cola
  # - node - use docker
# net/prod
  - thunderbird
  - firefox
  - xul-ext-lightning
  - nextcloud-client
  - nextcloud-client-dolphin
  - keepassxc
  - libreoffice
  - qownnotes
  - kwalletcli
  - go-for-it
# media
  - gpodder
  - vlc
  - mpv
  - cantata
  - digikam
  # - kdenlive
  # - audacity
# other
  - qemu-user
  - ansible
  - virt-manager
  - ssh-askpass
  - virt-viewer
  - qemu-kvm
  - bridge-utils
  - plasma-workspace-wallpapers
  - hplip-gui
  - skanlite



desktop_packages_snaps:
  - name: atom
    classic: yes
  - name: code
    classic: yes
  - name: sublime-text
    classic: yes
  - name: hugo
    channel: extended
  - name: kubectl
    classic: yes
  - name: lxd
  # - name: multipass
  #   options: --classic
  # - name: microk8s
  #   options: --classic
  # - name: android-studio
  #   options: --classic


# scrcpy



desktop_packages_deb:
  - name: skypeforlinux
    target: /usr/bin/skypeforlinux
    url: https://go.skype.com/skypeforlinux-64.deb
    dest: /tmp/skype.deb
    command: DEBIAN_FRONTEND=noninteractive apt install /tmp/skype.deb
  - name: googlechrome
    target: /usr/bin/google-chrome
    url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    dest: /tmp/chrome.deb
    command: DEBIAN_FRONTEND=noninteractive apt install /tmp/chrome.deb


desktop_packages_installer_user:
  - name: miniconda
    target: ~/miniconda3/bin/conda
    url: https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
    dest: ~/miniconda.sh
    command: bash ~/miniconda.sh -b -p $HOME/miniconda3








#  - golang-go
#  - mono
#  - libnotify-bin
# java

#dwarf fortress
#xterm
#libsdl-ttf2.0



#  - kphotoalbum
  # - shotwell
  # - wine


# python3-mutagen
# python3-gst-1.0
# python 3 PIL?

# clocify
#git, git tools
