
- name: remove old docker distributions
  apt:
    name:
      - docker.io
      - docker
    state: absent

- name: install some docker prerequisites
  apt:
    name:
      - libffi-dev
      - python-backports.ssl-match-hostname
      - python3-docker
      - python-docker
    state: present


- name: check if docker exists
  shell: which docker >/dev/null 2>&1
  register: docker_exists
  ignore_errors: yes
  failed_when: false


- name: install docker
  shell: curl -sSL https://get.docker.io/ | sh
  when: docker_exists.rc > 0


- name: install docker compose
  pip:
    name: docker-compose
    executable: pip3

- name: Add default user to docker group
  user:
    name: "{{default_user}}"
    groups: docker
    append: yes
