---


- name: ensure postgres data directory exists
  file:
    path: "{{ postgresql_data }}"
    state: directory
    mode: 0775
    owner: root
    group: root


- name: Copy pgsql compose file
  template:
    src: templates/docker-compose-pgsql.yml
    dest: /home/{{default_user}}/docker-compose-pgsql.yml
    mode: "0644"


- name: start postgresql using docker compose
  command: docker-compose -f /home/{{default_user}}/docker-compose-pgsql.yml up --detach
