---

hostname: frodo


mail_install_users:
  - rsmit

mail_account: gandi
mail_server: mail.gandi.net
mail_port: 587
mail_from: "{{hostname}}@{{private_my_mail_domain}}"
mail_username: "{{private_my_mail_username}}"
mail_password: "{{private_my_mail_password}}"

mail_root_email: "{{private_my_email}}"
mail_default_email: "{{private_my_email}}"
