---

- name: add pi to tty group for keyboard
  user:
    name: pi
    groups: tty
    append: yes


- name: install security policy files to enable power menu
  copy:
    src: files/power.pkla
    dest: /etc/polkit-1/localauthority/50-local.d/power.pkla
    mode: "0600"


- name: change tty permissions to allow kodi to read from keyboard
  copy:
    src: files/99-kodi-tty.rules
    dest: /etc/udev/rules.d/99-kodi-tty.rules
    mode: "0640"


- name: Install Kodi and all of its dependencies
  apt:
    name: kodi
    state: latest


- name: Set tvheadend username
  debconf:
    name=tvheadend
    question="tvheadend/admin_username"
    value="admin"
    vtype="string"
  register: tvheadend_result

# because password is masked ansible cannot figure out if we need this,
# so do it only if we had to change the username
- name: Set tvheadend password
  debconf:
    name=tvheadend
    question="tvheadend/admin_password"
    value="tvheadend"
    vtype="password"
  when: tvheadend_result.changed == True

- name: install tvheadend and its dependencies
  apt:
    name: tvheadend
    state: latest


- name: install kodi addons
  apt:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
      - kodi-pvr-hts
      - kodi-inputstream-adaptive
      - kodi-inputstream-rtmp

- name: copy systemd kodi service template
  copy:
    src: files/kodi.service
    dest: /etc/systemd/system/kodi.service
    mode: "0644"

- name: Create kodi settings directory
  file:
    path: /home/pi/.kodi/userdata
    state: directory
    owner: pi
    group: pi
    mode: 0755

- name: copy advanced settings
  copy:
    src: files/advancedsettings.xml
    dest: /home/pi/.kodi/userdata/advancedsettings.xml
    owner: pi
    group: pi
    mode: "0664"

- name: enable kodi but dont start it yet
  systemd:
    daemon-reload: true
    enabled: true
    name: kodi.service

- name: install various other media tools
  apt:
    name: "{{packages}}"
    state: latest
  vars:
    packages:
      - mpv
      - ffmpeg
      - rtmpdump
