
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-wallabag-environment
data:
  SYMFONY__ENV__DOMAIN_NAME: https://wallabag.smit.org.uk
  SYMFONY__ENV__DATABASE_DRIVER: pdo_mysql
  SYMFONY__ENV__DATABASE_HOST: my-wallabag-mariadb-service
  SYMFONY__ENV__DATABASE_PORT: "3306"
  SYMFONY__ENV__DATABASE_NAME: wallabag
  SYMFONY__ENV__DATABASE_USER: wallabag
  SYMFONY__ENV__DATABASE_PASSWORD: wallapass


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-wallabag
  labels:
    app: wallabag
spec:
  selector:
    matchLabels:
      app: wallabag
  replicas: 1
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
      - name: wallabag
        image: ejsmit/wallabag:2.3.8
        ports:
        - containerPort: 80
        envFrom:
          - configMapRef:
              name: my-wallabag-environment
          - configMapRef:
              name: my-wallabag-db-environment




---
apiVersion: v1
kind: Service        # Type of Kubernetes resource
metadata:
  name: my-wallabag-service # Name of the Kubernetes resource
  labels:            # Labels that will be applied to this resource
    app: wallabag
spec:
  ports:
  - port: 80       # Map incoming connections on port 6379 to the target port 6379 of the Pod
    targetPort: 80
  selector:          # Map any Pod with the specified labels to this service
    app: wallabag




---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: my-wallabag-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  tls:
  - hosts:
    - wallabag.smit.org.uk
    secretName: letsencrypt-certs
  rules:
  - host: wallabag.smit.org.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: my-wallabag-service
          servicePort: 80
