---



- name: Pull samba docker image
  docker_image:
    name: "{{samba_container}}"
    source: pull


- name: copy systemd samba template
  template:
    src: 'docker-samba.service'
    dest: '/etc/systemd/system/docker-samba.service'


- name: ensure share mount directory exists
  file:
    path: "{{ samba_mount }}"
    state: directory
    mode: 0775
    owner: root
    group: root


- name: ensure samba shares directories exist
  file:
    path: "{{ samba_mount }}/{{item}}"
    state: directory
    mode: 775
    owner: root
    group: root
  with_items: "{{ samba_shares_list }}"


- name: enable and start samba
  systemd:
    daemon-reload: true
    enabled: true
    state: started
    name: docker-samba.service
