



- name: ipv6 hardware based address
  lineinfile:
    dest: /etc/dhcpcd.conf
    state: present
    backup: yes
    regexp: '^slaac'
    line: 'slaac hwaddr'
  notify: reboot and wait




- name: add custom dns cnames configuration
  template:
    src: 90-pihole-custom-dns.conf
    dest: /etc/dnsmasq.d/90-pihole-custom-dns.conf
    owner: root
    group: root
    mode: 0644
