

# dont actually install it here.  I only make sure my ipv6 address
# is not constantly randomised, and then I restore the latest
# configuration backups.

# You then have to install and configure pihole yourself using the previous
# configration as guide.   some files can just be copied over, others
# you need to log into the user interface to change it.




- name: ipv6 hardware based address
  lineinfile:
    dest: /etc/dhcpcd.conf
    state: present
    backup: yes
    regexp: '^slaac'
    line: 'slaac hwaddr'
  notify: reboot and wait


- name: restore latest pihole backup
  command: /usr/local/bin/restic-restore-latest-to-home.sh
